---
- name: Get VPC peering connection facts
  ec2_vpc_peering_facts:
    aws_access_key: "{{ aws_access_key | default(omit) }}"
    aws_secret_key: "{{ aws_secret_key | default(omit) }}"
    region: "{{ aws_region }}"
    filters:
      status-code: active
      "tag:Name": "{{ vpc_pc_tag | upper }}"
  register: vpc_peering_facts
...
