---
- name: Get peering connection information
  include_role:
    name: aws_manage_vpc_peer
    tasks_from: get_vpc_peering_connection_facts
  vars:
    vpc_pc_tag: "{{ vpc_peer.aws_vpc_pc_name }}"

- name: Delete peering connection {{ vpc_peer.aws_vpc_pc_name }}
  ec2_vpc_peer:
    region: "{{ vpc_peer.aws_vpc_region }}"
    peering_id: "{{ vpc_peering_facts.result[0].vpc_peering_connection_id }}"
    state: absent
  when: vpc_peering_facts.result != []
...
